name: Test 1ES access

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  test:
    if: github.repository == 'microsoft/ntosebpfext'
    runs-on:
      - self-hosted
      - 1ES.Pool=ebpf-cicd-runner-pool-server-2019
      - 1ES.ImageOverride=server2022_v2
      - JobId=ntos-smoke-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |
          hostname
          Get-ComputerInfo |
            Select-Object WindowsProductName, WindowsVersion
